{{- if .Values.externaldns.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-dns
  namespace: {{ .Values.externaldns.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: external-dns
rules:
- apiGroups: [""]
  resources: ["services", "nodes"]
  verbs: ["get","watch","list"]
- apiGroups: [""]
  resources: ["pods", "nodes"]
  verbs: ["get","watch","list"]
- apiGroups: ["extensions"]
  resources: ["ingresses", "nodes"]
  verbs: ["get","watch","list"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: external-dns-viewer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-dns
subjects:
- kind: ServiceAccount
  name: external-dns
  namespace: {{ .Values.externaldns.namespace }}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: external-dns
  namespace: {{ .Values.externaldns.namespace }}
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      serviceAccountName: external-dns
      containers:
      - name: external-dns
        image: registry.opensource.zalan.do/teapot/external-dns:v0.5.4
        args:
        - --source=service
        - --source=ingress
        - --provider=aws
        - --registry=txt
        - --txt-owner-id=my-identifier
        - --compatibility=molecule # parse annotations used by wearemolecule/route53-kubernetes (i.e. domainName) for backwards compatibility
        - --policy=upsert-only # prevent ExternalDNS from deleting any records, omit to enable full synchronization
        # --domain-filter args will make ExternalDNS see only the hosted zones matching provided domain, omit to process all available hosted zones
        {{- range .Values.externaldns.hostedZones }}
        - --domain-filter={{ . }}
        {{- end }}
        #- --log-level=debug
        #- --aws-zone-type=public # only look at public hosted zones (valid values are public, private or no value for both)
{{- end }}
